### PR TITLE
Use global vectors for better multiprocessing and remove english_vectors

### PR DESCRIPTION
**Pull request by codez266**
* Experiments have shown that using global vectors in the vectorizers file works better for memory sharing - https://phabricator.wikimedia.org/T189364
* Removes the english_vectors script since we no longer need the vectors as a separate module.

### CODE REVIEW

**Comment by halfak** [comment]
Cool.  Does this work for dealing with the multiprocessing/shared memory issue?

**Comment by codez266** [comment]
With this, it does not OOM, but its not as fast as using the global keyword and memory usage seems to be high ~ 6GB. I'm not sure what is happening here, but we might need to revert back to using 'global'

**Comment by halfak** [comment]
Weird.  That doesn't make any sense.  Imports *are* globals.  Can you demonstrate this?

**Comment by codez266** [comment]
https://phabricator.wikimedia.org/T189364

**Comment by codez266** [comment]
Yeah, I had a similar idea but assigning any *big* thing in self leads to explosion of memory, which I think is because doing `self.xyz=` basically means we're causing the thing to pickle.

**Comment by codez266** [comment]
since it passes the speed test and looks good, going ahead to merge...

**Pull request merged**
